version: "3.8"
services:
  api-gateway:
    build: ./api-gateway
    container_name: microservices_container_api-gateway
    ports:
    - 7000:7000
    expose:
    - "7000"
    networks:
    - dev_network
    depends_on:
    - adminservices
    - customerservices
    - googleservices
    - miscservices
    - notificationservices
    - reportservices
    - subscriptionservices
    - voucherservices
  adminservices:
    build: ./adminservices
    container_name: microservices_container_adminservices
    ports:
    - 7001:7001
    expose:
    - "7001"
    networks:
    - dev_network
  customerservices:
    build: ./customerservices
    container_name: microservices_container_customerservices
    ports:
    - 7002:7002
    expose:
    - "7002"
    networks:
    - dev_network

  googleservices:
    build: ./googleservices
    container_name: microservices_container_googleservices
    ports:
      - "7003:7003"
    expose:
    - "7003"  
    networks:
      - dev_network

  miscservices:
    build: ./miscservices
    container_name: microservices_container_miscservices
    ports:
      - "7004:7004"
    expose:
    - "7004"  
    networks:
      - dev_network

  notificationservices:
    build: ./notificationservices
    container_name: microservices_container_notificationservices
    ports:
      - "7005:7005"
    expose:
    - "7005"
    networks:
      - dev_network 

  reportservices:
    build: ./reportservices
    container_name: microservices_container_reportservices
    ports:
      - "7006:7006"
    expose:
    - "7006"
    networks:
      - dev_network

  subscriptionservices:
    build: ./subscriptionservices
    container_name: microservices_container_subscriptionservices
    ports:
      - "7007:7007"
    expose:
    - "7007"
    networks:
      - dev_network

  voucherservices:
    build: ./voucherservices
    container_name: microservices_container_voucherservices
    ports:
      - "7008:7008"
    expose:
    - "7008"
    networks:
      - dev_network  
networks:
  dev_network:
    driver: bridge