apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api-service
  template:
    metadata:
      labels:
        app: backend-api-service
    spec:
      containers:
      - name: backend-api-service
        image: hordansodevops/reseller_customer_backend_api:latest
        ports:
        - containerPort: 7000
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: api-config