apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-customerapi-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-customerapi-service
  template:
    metadata:
      labels:
        app: backend-customerapi-service
    spec:
      containers:
      - name: backend-customerapi-service
        image: hordansodevops/reseller_customer_backend_customerservices:latest
        ports:
        - containerPort: 7002
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: customerservices-config