apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-paymentapi-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-paymentapi-service
  template:
    metadata:
      labels:
        app: backend-paymentapi-service
    spec:
      containers:
      - name: backend-paymentapi-service
        image: hordansodevops/reseller_customer_backend_paymentservices:latest
        ports:
        - containerPort: 7003
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: paymentservices-config