apiVersion: v1
kind: Service
metadata:
  name: backend-subscriptionapi-service
spec:
  selector:
    app: backend-subscriptionapi-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7007
